trino:
  target: dev
  outputs:
    dev:
      type: trino
      user: admin
      host: localhost
      port: 8080
      database: warehouse
      schema: bronze
      threads: 1

spark:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: localhost
      port: 10000
      schema: silver
      connect_retries: 5
      connect_timeout: 60
      retry_all: true

gold:
  target: dev
  outputs:
    dev:
      type: trino
      user: admin
      host: localhost
      port: 8080
      database: de_psql
      schema: gold
      threads: 1